In [31]:
# ------------------------------------------------------------
# 1. Setup & Imports
# ------------------------------------------------------------
"""
Notebook: 03_data_model_preparation.ipynb
Author: James O. Adeshina
Date: October 2025

Objective:
----------
Prepare the Monzo Sentiment dataset for analytical modeling by:
- Engineering new features
- Creating dimensional tables
- Exporting BigQuery-ready schemas
"""

import pandas as pd
import numpy as np
import os

In [32]:

# === Paths ===
DATA_PATH = "../data/processed/Monzo_Sentiment_Scored.csv"
WAREHOUSE_PATH = "../data/warehouse/"
os.makedirs(WAREHOUSE_PATH, exist_ok=True)

# === Load dataset ===
print("📂 Loading sentiment-scored dataset...")
monzo_df = pd.read_csv(DATA_PATH)
print(f"✅ Loaded {len(monzo_df):,} rows and {monzo_df.shape[1]} columns.")
monzo_df.head(3)

📂 Loading sentiment-scored dataset...
✅ Loaded 31,625 rows and 32 columns.

,review_date,rating,review_title,review_text,author_name,app_version,country,review_language,developer_reply_text,developer_reply_date,...,ux_navigation_sentiment,ux_performance_sentiment,ux_accessibility_sentiment,ux_emotional_sentiment,ux_health_score,csat_approx,ces_approx,task_success_inferred,ux_pain_point_flag,ux_sentiment_level
0,2025-10-01 06:03:52+00:00,5,Read this truthful review,This banking app is the best for kids because ...,Thegamingmommyreviw,6.46.0,gb,en,NaN,NaN,...,NaN,NaN,0.9578,0.9578,0.9578,99.16,65,NaN,False,Positive
1,2025-09-30 15:17:27+00:00,5,Cracking easy to use bank,Don’t tend to use the perks other than get sue...,Kar3n2,6.46.0,gb,en,NaN,NaN,...,NaN,NaN,NaN,NaN,0.7650,95.30,85,NaN,False,Positive
2,2025-09-30 15:01:26+00:00,5,Monzo is great,The best bank I have ever use. It is honestly ...,Kira mella,6.46.0,gb,en,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,98.86,65,NaN,False,Unknown

In [33]:
# ------------------------------------------------------------
# 2. Feature Engineering
# ------------------------------------------------------------

print("🧠 Engineering new analytical features...")

# Review length (in characters)
monzo_df["review_length"] = monzo_df["review_text"].astype(str).str.len()

# Flag developer replies
monzo_df["has_reply"] = monzo_df["developer_reply_text"].notna().astype(int)

# Rating category for easier analysis
def rating_category(r):
    if r >= 4: return "High"
    elif r == 3: return "Medium"
    else: return "Low"

monzo_df["rating_category"] = monzo_df["rating"].apply(rating_category)

# Review date parsing
monzo_df["review_date"] = pd.to_datetime(monzo_df["review_date"], errors="coerce", utc=True)
monzo_df["review_year"] = monzo_df["review_date"].dt.year
monzo_df["review_month"] = monzo_df["review_date"].dt.month
monzo_df["review_week"] = monzo_df["review_date"].dt.isocalendar().week

print("✅ Feature engineering complete.")
monzo_df[["rating", "rating_category", "review_length", "has_reply"]].head(3)

🧠 Engineering new analytical features...
✅ Feature engineering complete.

   rating rating_category  review_length  has_reply
0       5            High            411          0
1       5            High            125          0
2       5            High             75          0

In [34]:
# Summary of engineered features
summary = {
    "Total Reviews": len(monzo_df),
    "Missing Review Text": monzo_df["review_text"].isna().sum(),
    "Avg. Review Length": monzo_df["review_length"].mean(),
    "Reviews with Developer Reply": monzo_df["has_reply"].sum(),
    "Rating Category Counts": monzo_df["rating_category"].value_counts().to_dict(),
    "Years Covered": monzo_df["review_year"].dropna().unique().tolist()
}

from pprint import pprint
pprint(summary)

{'Avg. Review Length': 133.4543557312253,
 'Missing Review Text': 0,
 'Rating Category Counts': {'High': 21629, 'Low': 8818, 'Medium': 1178},
 'Reviews with Developer Reply': 2595,
 'Total Reviews': 31625,
 'Years Covered': [2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016]}

In [35]:
# ------------------------------------------------------------
# 3. Dimensional Tables
# ------------------------------------------------------------

print("🧩 Creating dimension tables...")

# Platform dimension
dim_platform = monzo_df[["platform"]].drop_duplicates().reset_index(drop=True)
dim_platform["platform_id"] = dim_platform.index + 1

# Version dimension
dim_version = monzo_df[["app_version"]].drop_duplicates().reset_index(drop=True)
dim_version["version_id"] = dim_version.index + 1

# Date dimension
dim_date = monzo_df[["review_date", "review_year", "review_month", "review_week"]].drop_duplicates()
dim_date = dim_date.sort_values("review_date").reset_index(drop=True)
dim_date["date_id"] = dim_date.index + 1

# Sentiment dimension
dim_sentiment = (
    monzo_df[["sentiment_label"]]
    .drop_duplicates()
    .reset_index(drop=True)
)
dim_sentiment["sentiment_id"] = dim_sentiment.index + 1

# UX Sentiment Level dimension
dim_ux = (
    monzo_df[["ux_sentiment_level"]]
    .drop_duplicates()
    .reset_index(drop=True)
)
dim_ux["ux_id"] = dim_ux.index + 1

print(f"   - UX Sentiment Level: {len(dim_ux)}")


print("✅ Dimensions created:")
print(f"   - Platform: {len(dim_platform)}")
print(f"   - Version: {len(dim_version)}")
print(f"   - Date: {len(dim_date)}")
print(f"   - Sentiment: {len(dim_sentiment)}")

🧩 Creating dimension tables...
   - UX Sentiment Level: 4
✅ Dimensions created:
   - Platform: 2
   - Version: 597
   - Date: 31615
   - Sentiment: 3

In [49]:
# ------------------------------------------------------------
# 4. FactReviews Table
# ------------------------------------------------------------

print("🧮 Building FactReviews table...")

fact_reviews = monzo_df.copy()

# Merge ID references from dimensions
fact_reviews = fact_reviews.merge(dim_platform, on="platform", how="left")
fact_reviews = fact_reviews.merge(dim_version, on="app_version", how="left")
fact_reviews = fact_reviews.merge(dim_date, on="review_date", how="left")
fact_reviews = fact_reviews.merge(dim_sentiment, on="sentiment_label", how="left")

# 🩹 FIX: Safely join DimUX — avoid many-to-many explosion
# If multiple rows per sentiment level exist, keep only one representative row
dim_ux_deduped = dim_ux.drop_duplicates(subset=["ux_sentiment_level"])[["ux_sentiment_level", "ux_id"]]

fact_reviews = fact_reviews.merge(dim_ux_deduped, on="ux_sentiment_level", how="left")

# List of potential columns to include
candidate_columns = [
    "review_date", "rating", "rating_category", "review_text",
    "review_length", "has_reply", "sentiment_score", "sentiment_label",
    "csat_approx", "ces_approx", "task_success_inferred",
    # keep all raw UX signal columns so infer_ux_category can see them
    "ux_usability_sentiment", "ux_navigation_sentiment",
    "ux_performance_sentiment", "ux_accessibility_sentiment",
    "ux_emotional_sentiment",
    "ux_health_score", "ux_sentiment_level", "ux_pain_point_flag",
    "is_pseudonymized", "platform_id", "version_id", "date_id",
    "sentiment_id", "ux_id"
]


# Keep only columns that exist in the dataframe
existing_columns = [col for col in candidate_columns if col in fact_reviews.columns]

# Select only valid ones
fact_reviews = fact_reviews[existing_columns]

print(f"✅ FactReviews shape: {fact_reviews.shape}")
display(fact_reviews.head(3))

🧮 Building FactReviews table...
✅ FactReviews shape: (31625, 24)

,review_date,rating,rating_category,review_text,review_length,has_reply,sentiment_score,sentiment_label,csat_approx,ces_approx,...,ux_accessibility_sentiment,ux_emotional_sentiment,ux_health_score,ux_sentiment_level,ux_pain_point_flag,platform_id,version_id,date_id,sentiment_id,ux_id
0,2025-10-01 06:03:52+00:00,5,High,This banking app is the best for kids because ...,411,0,0.9578,positive,99.16,65,...,0.9578,0.9578,0.9578,Positive,False,1,1,31615,1,1
1,2025-09-30 15:17:27+00:00,5,High,Don’t tend to use the perks other than get sue...,125,0,0.7650,positive,95.30,85,...,NaN,NaN,0.7650,Positive,False,1,1,31614,1,1
2,2025-09-30 15:01:26+00:00,5,High,The best bank I have ever use. It is honestly ...,75,0,0.9432,positive,98.86,65,...,NaN,NaN,NaN,Unknown,False,1,1,31613,1,3

In [50]:
from IPython.display import display

print("Dim Shapes")

display(fact_reviews.head(3))
display(dim_platform.head(3))
display(dim_version.head(3))
display(dim_date.head(3))
display(dim_sentiment.head(3))
display(dim_ux.head(3))

Dim Shapes

,review_date,rating,rating_category,review_text,review_length,has_reply,sentiment_score,sentiment_label,csat_approx,ces_approx,...,ux_accessibility_sentiment,ux_emotional_sentiment,ux_health_score,ux_sentiment_level,ux_pain_point_flag,platform_id,version_id,date_id,sentiment_id,ux_id
0,2025-10-01 06:03:52+00:00,5,High,This banking app is the best for kids because ...,411,0,0.9578,positive,99.16,65,...,0.9578,0.9578,0.9578,Positive,False,1,1,31615,1,1
1,2025-09-30 15:17:27+00:00,5,High,Don’t tend to use the perks other than get sue...,125,0,0.7650,positive,95.30,85,...,NaN,NaN,0.7650,Positive,False,1,1,31614,1,1
2,2025-09-30 15:01:26+00:00,5,High,The best bank I have ever use. It is honestly ...,75,0,0.9432,positive,98.86,65,...,NaN,NaN,NaN,Unknown,False,1,1,31613,1,3

  platform  platform_id
0      iOS            1
1  Android            2

  app_version  version_id
0      6.46.0           1
1      6.45.0           2
2      6.44.0           3

                review_date  review_year  review_month  review_week  date_id
0 2016-02-26 22:15:55+00:00         2016             2            8        1
1 2016-03-01 19:48:37+00:00         2016             3            9        2
2 2016-03-03 14:56:53+00:00         2016             3            9        3

  sentiment_label  sentiment_id
0        positive             1
1         neutral             2
2        negative             3

,ux_usability_sentiment,ux_navigation_sentiment,ux_performance_sentiment,ux_accessibility_sentiment,ux_emotional_sentiment,ux_health_score,ux_pain_point_flag,ux_sentiment_level,ux_id
0,NaN,NaN,NaN,0.9578,0.9578,0.9578,False,Positive,1
1,0.765,NaN,NaN,NaN,NaN,0.7650,False,Positive,2
2,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,3

In [51]:
from IPython.display import display

# Assuming you have already loaded these DataFrames: fact_reviews, dim_platform, etc.
print("Dim Shapes")

# Display row counts and first three rows for each DataFrame
print(f"fact_reviews: {fact_reviews.shape[0]} rows")
display(fact_reviews.head(12))

print(f"dim_platform: {dim_platform.shape[0]} rows")
display(dim_platform.head(3))

print(f"dim_version: {dim_version.shape[0]} rows")
display(dim_version.head(3))

print(f"dim_date: {dim_date.shape[0]} rows")
display(dim_date.head(3))

print(f"dim_sentiment: {dim_sentiment.shape[0]} rows")
display(dim_sentiment.head(3))

print(f"dim_ux: {dim_ux.shape[0]} rows")
display(dim_ux.head(3))

Dim Shapes
fact_reviews: 31625 rows

,review_date,rating,rating_category,review_text,review_length,has_reply,sentiment_score,sentiment_label,csat_approx,ces_approx,...,ux_accessibility_sentiment,ux_emotional_sentiment,ux_health_score,ux_sentiment_level,ux_pain_point_flag,platform_id,version_id,date_id,sentiment_id,ux_id
0,2025-10-01 06:03:52+00:00,5,High,This banking app is the best for kids because ...,411,0,0.9578,positive,99.16,65,...,0.9578,0.9578,0.9578,Positive,False,1,1,31615,1,1
1,2025-09-30 15:17:27+00:00,5,High,Don’t tend to use the perks other than get sue...,125,0,0.7650,positive,95.30,85,...,NaN,NaN,0.7650,Positive,False,1,1,31614,1,1
2,2025-09-30 15:01:26+00:00,5,High,The best bank I have ever use. It is honestly ...,75,0,0.9432,positive,98.86,65,...,NaN,NaN,NaN,Unknown,False,1,1,31613,1,3
3,2025-09-30 14:40:05+00:00,1,Low,Monzo behaved like scammers. After establishin...,355,0,0.8275,positive,48.55,65,...,NaN,NaN,NaN,Unknown,False,1,1,31612,1,3
4,2025-09-29 20:51:54+00:00,5,High,Really good everyday bank comes with added ben...,113,0,0.8588,positive,97.18,65,...,NaN,NaN,NaN,Unknown,False,1,1,31611,1,3
5,2025-09-29 19:55:42+00:00,4,High,Change how you display the transaction dates. ...,280,0,0.0000,neutral,68.00,40,...,NaN,NaN,NaN,Unknown,False,1,1,31610,2,3
6,2025-09-29 15:33:04+00:00,5,High,I love Monzo so much that I’ve now switched al...,87,0,0.8555,positive,97.11,65,...,NaN,0.8555,0.8555,Positive,False,1,1,31609,1,1
7,2025-09-28 18:13:54+00:00,5,High,just refer everyone u know for infinite tennrtd,47,0,0.0000,neutral,80.00,65,...,NaN,NaN,NaN,Unknown,False,1,1,31608,2,3
8,2025-09-28 09:55:14+00:00,1,Low,i clicked on the wrong thing on accident and n...,234,0,-0.9496,negative,13.01,65,...,NaN,NaN,NaN,Unknown,False,1,1,31607,3,3
9,2025-09-27 19:33:34+00:00,5,High,Excellent app for day to day banking. I pay fo...,211,0,0.9450,positive,98.90,65,...,NaN,0.9450,0.9450,Positive,False,1,1,31606,1,1
10,2025-09-27 12:49:44+00:00,1,Low,I updated it and can’t access it without crash...,87,0,0.6222,positive,44.44,65,...,NaN,NaN,NaN,Unknown,False,1,1,31605,1,3
11,2025-09-27 12:12:40+00:00,1,Low,No explanation just closed my account after be...,162,0,-0.8747,negative,14.51,65,...,NaN,NaN,NaN,Unknown,False,1,1,31604,3,3

dim_platform: 2 rows

  platform  platform_id
0      iOS            1
1  Android            2

dim_version: 597 rows

  app_version  version_id
0      6.46.0           1
1      6.45.0           2
2      6.44.0           3

dim_date: 31615 rows

                review_date  review_year  review_month  review_week  date_id
0 2016-02-26 22:15:55+00:00         2016             2            8        1
1 2016-03-01 19:48:37+00:00         2016             3            9        2
2 2016-03-03 14:56:53+00:00         2016             3            9        3

dim_sentiment: 3 rows

  sentiment_label  sentiment_id
0        positive             1
1         neutral             2
2        negative             3

dim_ux: 4975 rows

,ux_usability_sentiment,ux_navigation_sentiment,ux_performance_sentiment,ux_accessibility_sentiment,ux_emotional_sentiment,ux_health_score,ux_pain_point_flag,ux_sentiment_level,ux_id
0,NaN,NaN,NaN,0.9578,0.9578,0.9578,False,Positive,1
1,0.765,NaN,NaN,NaN,NaN,0.7650,False,Positive,2
2,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,3

In [52]:
dim_ux = monzo_df[[
    "ux_usability_sentiment",
    "ux_navigation_sentiment",
    "ux_performance_sentiment",
    "ux_accessibility_sentiment",
    "ux_emotional_sentiment",
    "ux_health_score",
    "ux_pain_point_flag",
    "ux_sentiment_level"
]].drop_duplicates().reset_index(drop=True)

dim_ux["ux_id"] = dim_ux.index + 1

In [53]:
# fact_reviews = fact_reviews.merge(dim_ux, on="ux_sentiment_level", how="left")

In [54]:
print(f"✅ Loaded {len(fact_reviews):,} rows and {fact_reviews.shape[1]} columns.")

✅ Loaded 31,625 rows and 24 columns.

In [55]:
print(f"✅ Loaded {len(dim_ux):,} rows and {dim_ux.shape[1]} columns.")

✅ Loaded 4,975 rows and 9 columns.

In [56]:
# ------------------------------------------------------------
# Derive dominant UX category for each review
# ------------------------------------------------------------

def infer_ux_category(row):
    scores = {
        "usability": row.get("ux_usability_sentiment", None),
        "navigation": row.get("ux_navigation_sentiment", None),
        "performance": row.get("ux_performance_sentiment", None),
        "accessibility": row.get("ux_accessibility_sentiment", None),
        "emotional": row.get("ux_emotional_sentiment", None),
    }
    # Drop NaNs and find max
    valid_scores = {k: v for k, v in scores.items() if pd.notna(v)}
    if not valid_scores:
        return None
    return max(valid_scores, key=valid_scores.get)

fact_reviews["ux_category"] = fact_reviews.apply(infer_ux_category, axis=1)

In [57]:
fact_reviews["ux_category"].value_counts(dropna=False)

ux_category
None             21819
usability         5040
emotional         2945
navigation        1288
performance        485
accessibility       48
Name: count, dtype: int64

In [61]:
print(f"✅ Loaded {len(dim_ux):,} rows and {dim_ux.shape[1]} columns.")

✅ Loaded 4,322 rows and 5 columns.

In [65]:
# ------------------------------------------------------------
# Now create DimUX cleanly
# ------------------------------------------------------------
dim_ux = fact_reviews[
    ["ux_id","ux_usability_sentiment","ux_navigation_sentiment","ux_performance_sentiment","ux_accessibility_sentiment","ux_emotional_sentiment","ux_health_score","ux_pain_point_flag","ux_sentiment_level","ux_category"]
].drop_duplicates().reset_index(drop=True)
dim_ux["ux_id"] = dim_ux.index + 1

In [66]:
print(f"dim_ux: {dim_ux.shape[0]} rows")
display(dim_ux.head(3))

dim_ux: 4975 rows

,ux_id,ux_usability_sentiment,ux_navigation_sentiment,ux_performance_sentiment,ux_accessibility_sentiment,ux_emotional_sentiment,ux_health_score,ux_pain_point_flag,ux_sentiment_level,ux_category
0,1,NaN,NaN,NaN,0.9578,0.9578,0.9578,False,Positive,accessibility
1,2,0.765,NaN,NaN,NaN,NaN,0.7650,False,Positive,usability
2,3,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,None

In [67]:
print(fact_reviews['ux_category'].value_counts(dropna=False))

ux_category
None             21819
usability         5040
emotional         2945
navigation        1288
performance        485
accessibility       48
Name: count, dtype: int64

In [73]:
# ------------------------------------------------------------
# Build DimUX (refined)
# ------------------------------------------------------------
print("🧩 Rebuilding DimUX...")

# Group by ux_category and summarise UX signals
dim_ux = (
    fact_reviews.groupby("ux_category", dropna=False)
    .agg({
        "ux_usability_sentiment": "mean",
        "ux_navigation_sentiment": "mean",
        "ux_performance_sentiment": "mean",
        "ux_accessibility_sentiment": "mean",
        "ux_emotional_sentiment": "mean",
        "ux_health_score": "mean",
        "ux_sentiment_level": lambda x: x.mode().iloc[0] if not x.mode().empty else "Unknown",
        "ux_pain_point_flag": "mean",
        "review_text": "count"
    })
    .rename(columns={"review_text": "count_reviews"})
    .reset_index()
)

# Replace NaN category label with "None"
dim_ux["ux_category"] = dim_ux["ux_category"].fillna("None")

# Assign unique ID
dim_ux["ux_id"] = dim_ux.index + 1

# Reorder columns neatly
dim_ux = dim_ux[
    [
        "ux_id", "ux_category",
        "ux_usability_sentiment", "ux_navigation_sentiment",
        "ux_performance_sentiment", "ux_accessibility_sentiment",
        "ux_emotional_sentiment", "ux_health_score",
        "ux_sentiment_level", "ux_pain_point_flag",
        "count_reviews"
    ]
]

print(f"✅ DimUX shape: {dim_ux.shape}")
display(dim_ux.head())

🧩 Rebuilding DimUX...
✅ DimUX shape: (6, 11)

,ux_id,ux_category,ux_usability_sentiment,ux_navigation_sentiment,ux_performance_sentiment,ux_accessibility_sentiment,ux_emotional_sentiment,ux_health_score,ux_sentiment_level,ux_pain_point_flag,count_reviews
0,1,accessibility,NaN,NaN,NaN,0.411654,0.654758,0.411654,Positive,0.208333,48
1,2,emotional,NaN,NaN,NaN,NaN,0.593434,0.593434,Positive,0.121902,2945
2,3,navigation,NaN,0.133696,0.054493,0.549821,0.296382,0.133696,Negative,0.398292,1288
3,4,performance,NaN,NaN,-0.061055,0.690100,0.262168,-0.061055,Negative,0.517526,485
4,5,usability,0.685454,0.602454,0.584355,0.777852,0.829872,0.685454,Positive,0.054365,5040

In [74]:
print(dim_ux['ux_category'].value_counts(dropna=False))

ux_category
accessibility    1
emotional        1
navigation       1
performance      1
usability        1
None             1
Name: count, dtype: int64

In [76]:
from IPython.display import display

print("Dim Shapes")

display(fact_reviews.head(6))
display(dim_platform.head(6))
display(dim_version.head(6))
display(dim_date.head(6))
display(dim_sentiment.head(6))
display(dim_ux.head(6))

Dim Shapes

,review_date,rating,rating_category,review_text,review_length,has_reply,sentiment_score,sentiment_label,csat_approx,ces_approx,...,ux_emotional_sentiment,ux_health_score,ux_sentiment_level,ux_pain_point_flag,platform_id,version_id,date_id,sentiment_id,ux_id,ux_category
0,2025-10-01 06:03:52+00:00,5,High,This banking app is the best for kids because ...,411,0,0.9578,positive,99.16,65,...,0.9578,0.9578,Positive,False,1,1,31615,1,1,accessibility
1,2025-09-30 15:17:27+00:00,5,High,Don’t tend to use the perks other than get sue...,125,0,0.7650,positive,95.30,85,...,NaN,0.7650,Positive,False,1,1,31614,1,1,usability
2,2025-09-30 15:01:26+00:00,5,High,The best bank I have ever use. It is honestly ...,75,0,0.9432,positive,98.86,65,...,NaN,NaN,Unknown,False,1,1,31613,1,3,None
3,2025-09-30 14:40:05+00:00,1,Low,Monzo behaved like scammers. After establishin...,355,0,0.8275,positive,48.55,65,...,NaN,NaN,Unknown,False,1,1,31612,1,3,None
4,2025-09-29 20:51:54+00:00,5,High,Really good everyday bank comes with added ben...,113,0,0.8588,positive,97.18,65,...,NaN,NaN,Unknown,False,1,1,31611,1,3,None
5,2025-09-29 19:55:42+00:00,4,High,Change how you display the transaction dates. ...,280,0,0.0000,neutral,68.00,40,...,NaN,NaN,Unknown,False,1,1,31610,2,3,None

  platform  platform_id
0      iOS            1
1  Android            2

  app_version  version_id
0      6.46.0           1
1      6.45.0           2
2      6.44.0           3
3      6.43.1           4
4      6.43.0           5
5      6.42.0           6

                review_date  review_year  review_month  review_week  date_id
0 2016-02-26 22:15:55+00:00         2016             2            8        1
1 2016-03-01 19:48:37+00:00         2016             3            9        2
2 2016-03-03 14:56:53+00:00         2016             3            9        3
3 2016-03-05 20:14:42+00:00         2016             3            9        4
4 2016-03-17 10:10:51+00:00         2016             3           11        5
5 2016-03-17 10:17:08+00:00         2016             3           11        6

  sentiment_label  sentiment_id
0        positive             1
1         neutral             2
2        negative             3

,ux_id,ux_category,ux_usability_sentiment,ux_navigation_sentiment,ux_performance_sentiment,ux_accessibility_sentiment,ux_emotional_sentiment,ux_health_score,ux_sentiment_level,ux_pain_point_flag,count_reviews
0,1,accessibility,NaN,NaN,NaN,0.411654,0.654758,0.411654,Positive,0.208333,48
1,2,emotional,NaN,NaN,NaN,NaN,0.593434,0.593434,Positive,0.121902,2945
2,3,navigation,NaN,0.133696,0.054493,0.549821,0.296382,0.133696,Negative,0.398292,1288
3,4,performance,NaN,NaN,-0.061055,0.690100,0.262168,-0.061055,Negative,0.517526,485
4,5,usability,0.685454,0.602454,0.584355,0.777852,0.829872,0.685454,Positive,0.054365,5040
5,6,None,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,0.000000,21819

In [77]:
# ------------------------------------------------------------
# 5. Export Dimensional & Fact Tables
# ------------------------------------------------------------

import os
import pandas as pd

# --- Setup paths ---
FORMATS = ["csv", "gzip", "parquet"]
for fmt in FORMATS:
    os.makedirs(os.path.join(WAREHOUSE_PATH, fmt), exist_ok=True)

# --- Tables to export ---
tables = {
    "FactReviews": fact_reviews,
    "DimPlatform": dim_platform,
    "DimVersion": dim_version,
    "DimDate": dim_date,
    "DimSentiment": dim_sentiment,
    "DimUX": dim_ux
}

# --- Export loop ---
print("💾 Exporting all warehouse tables in CSV, GZIP, and Parquet formats...")

for name, table in tables.items():
    print(f"\n📦 Exporting {name} ({table.shape[0]} rows, {table.shape[1]} cols)...")

    # 1️⃣ CSV
    csv_path = os.path.join(WAREHOUSE_PATH, "csv", f"{name}.csv")
    table.to_csv(csv_path, index=False, encoding="utf-8")

    # 2️⃣ GZIP
    gzip_path = os.path.join(WAREHOUSE_PATH, "gzip", f"{name}.csv.gz")
    table.to_csv(gzip_path, index=False, compression="gzip", encoding="utf-8")

    # 3️⃣ Parquet
    parquet_path = os.path.join(WAREHOUSE_PATH, "parquet", f"{name}.parquet")
    table.to_parquet(parquet_path, index=False, compression="snappy")

    # Size check
    size_csv = os.path.getsize(csv_path) / (1024**3)
    size_gz = os.path.getsize(gzip_path) / (1024**3)
    size_pq = os.path.getsize(parquet_path) / (1024**3)

    print(f"   • CSV:   {size_csv:.2f} GB")
    print(f"   • GZIP:  {size_gz:.2f} GB")
    print(f"   • PARQ:  {size_pq:.2f} GB")

print("\n✅ All export formats generated successfully.")
print(f"📁 Location: {WAREHOUSE_PATH}")

💾 Exporting all warehouse tables in CSV, GZIP, and Parquet formats...

📦 Exporting FactReviews (31625 rows, 25 cols)...
   • CSV:   0.01 GB
   • GZIP:  0.00 GB
   • PARQ:  0.00 GB

📦 Exporting DimPlatform (2 rows, 2 cols)...
   • CSV:   0.00 GB
   • GZIP:  0.00 GB
   • PARQ:  0.00 GB

📦 Exporting DimVersion (597 rows, 2 cols)...
   • CSV:   0.00 GB
   • GZIP:  0.00 GB
   • PARQ:  0.00 GB

📦 Exporting DimDate (31615 rows, 5 cols)...
   • CSV:   0.00 GB
   • GZIP:  0.00 GB
   • PARQ:  0.00 GB

📦 Exporting DimSentiment (3 rows, 2 cols)...
   • CSV:   0.00 GB
   • GZIP:  0.00 GB
   • PARQ:  0.00 GB

📦 Exporting DimUX (6 rows, 11 cols)...
   • CSV:   0.00 GB
   • GZIP:  0.00 GB
   • PARQ:  0.00 GB

✅ All export formats generated successfully.
📁 Location: ../data/warehouse/