In [2]:
# ------------------------------------------------------------
# 1. Setup & Imports
# ------------------------------------------------------------
"""
Notebook: 03_data_model_preparation.ipynb
Author: James O. Adeshina
Date: October 2025

Objective:
----------
Prepare the Monzo Sentiment dataset for analytical modeling by:
- Engineering new features
- Creating dimensional tables
- Exporting BigQuery-ready schemas
"""

import pandas as pd
import numpy as np
import os

In [3]:

# === Paths ===
DATA_PATH = "../data/processed/Monzo_Sentiment_Scored.csv"
WAREHOUSE_PATH = "../data/warehouse/"
os.makedirs(WAREHOUSE_PATH, exist_ok=True)

# === Load dataset ===
print("📂 Loading sentiment-scored dataset...")
monzo_df = pd.read_csv(DATA_PATH)
print(f"✅ Loaded {len(monzo_df):,} rows and {monzo_df.shape[1]} columns.")
monzo_df.head(3)

📂 Loading sentiment-scored dataset...
✅ Loaded 31,625 rows and 32 columns.

,review_date,rating,review_title,review_text,author_name,app_version,country,review_language,developer_reply_text,developer_reply_date,...,ux_navigation_sentiment,ux_performance_sentiment,ux_accessibility_sentiment,ux_emotional_sentiment,ux_health_score,csat_approx,ces_approx,task_success_inferred,ux_pain_point_flag,ux_sentiment_level
0,2025-10-01 06:03:52+00:00,5,Read this truthful review,This banking app is the best for kids because ...,Thegamingmommyreviw,6.46.0,gb,en,NaN,NaN,...,NaN,NaN,0.9578,0.9578,0.9578,99.16,65,NaN,False,Positive
1,2025-09-30 15:17:27+00:00,5,Cracking easy to use bank,Don’t tend to use the perks other than get sue...,Kar3n2,6.46.0,gb,en,NaN,NaN,...,NaN,NaN,NaN,NaN,0.7650,95.30,85,NaN,False,Positive
2,2025-09-30 15:01:26+00:00,5,Monzo is great,The best bank I have ever use. It is honestly ...,Kira mella,6.46.0,gb,en,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,98.86,65,NaN,False,Unknown

In [4]:
# ------------------------------------------------------------
# 2. Feature Engineering
# ------------------------------------------------------------

print("🧠 Engineering new analytical features...")

# Review length (in characters)
monzo_df["review_length"] = monzo_df["review_text"].astype(str).str.len()

# Flag developer replies
monzo_df["has_reply"] = monzo_df["developer_reply_text"].notna().astype(int)

# Rating category for easier analysis
def rating_category(r):
    if r >= 4: return "High"
    elif r == 3: return "Medium"
    else: return "Low"

monzo_df["rating_category"] = monzo_df["rating"].apply(rating_category)

# Review date parsing
monzo_df["review_date"] = pd.to_datetime(monzo_df["review_date"], errors="coerce", utc=True)
monzo_df["review_year"] = monzo_df["review_date"].dt.year
monzo_df["review_month"] = monzo_df["review_date"].dt.month
monzo_df["review_week"] = monzo_df["review_date"].dt.isocalendar().week

print("✅ Feature engineering complete.")
monzo_df[["rating", "rating_category", "review_length", "has_reply"]].head(3)

🧠 Engineering new analytical features...
✅ Feature engineering complete.

   rating rating_category  review_length  has_reply
0       5            High            411          0
1       5            High            125          0
2       5            High             75          0

In [5]:
# Summary of engineered features
summary = {
    "Total Reviews": len(monzo_df),
    "Missing Review Text": monzo_df["review_text"].isna().sum(),
    "Avg. Review Length": monzo_df["review_length"].mean(),
    "Reviews with Developer Reply": monzo_df["has_reply"].sum(),
    "Rating Category Counts": monzo_df["rating_category"].value_counts().to_dict(),
    "Years Covered": monzo_df["review_year"].dropna().unique().tolist()
}

from pprint import pprint
pprint(summary)

{'Avg. Review Length': 133.4543557312253,
 'Missing Review Text': 0,
 'Rating Category Counts': {'High': 21629, 'Low': 8818, 'Medium': 1178},
 'Reviews with Developer Reply': 2595,
 'Total Reviews': 31625,
 'Years Covered': [2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016]}

In [6]:
# ------------------------------------------------------------
# 3. Dimensional Tables
# ------------------------------------------------------------

print("🧩 Creating dimension tables...")

# Platform dimension
dim_platform = monzo_df[["platform"]].drop_duplicates().reset_index(drop=True)
dim_platform["platform_id"] = dim_platform.index + 1

# Version dimension
dim_version = monzo_df[["app_version"]].drop_duplicates().reset_index(drop=True)
dim_version["version_id"] = dim_version.index + 1

# Date dimension
dim_date = monzo_df[["review_date", "review_year", "review_month", "review_week"]].drop_duplicates()
dim_date = dim_date.sort_values("review_date").reset_index(drop=True)
dim_date["date_id"] = dim_date.index + 1

# Sentiment dimension
dim_sentiment = (
    monzo_df[["sentiment_label"]]
    .drop_duplicates()
    .reset_index(drop=True)
)
dim_sentiment["sentiment_id"] = dim_sentiment.index + 1

# UX Sentiment Level dimension
dim_ux = (
    monzo_df[["ux_sentiment_level"]]
    .drop_duplicates()
    .reset_index(drop=True)
)
dim_ux["ux_id"] = dim_ux.index + 1

print(f"   - UX Sentiment Level: {len(dim_ux)}")


print("✅ Dimensions created:")
print(f"   - Platform: {len(dim_platform)}")
print(f"   - Version: {len(dim_version)}")
print(f"   - Date: {len(dim_date)}")
print(f"   - Sentiment: {len(dim_sentiment)}")

🧩 Creating dimension tables...
   - UX Sentiment Level: 4
✅ Dimensions created:
   - Platform: 2
   - Version: 597
   - Date: 31615
   - Sentiment: 3

In [7]:
# ------------------------------------------------------------
# 4. FactReviews Table
# ------------------------------------------------------------

print("🧮 Building FactReviews table...")

fact_reviews = monzo_df.copy()

# Merge ID references from dimensions
fact_reviews = fact_reviews.merge(dim_platform, on="platform", how="left")
fact_reviews = fact_reviews.merge(dim_version, on="app_version", how="left")
fact_reviews = fact_reviews.merge(dim_date, on="review_date", how="left")
fact_reviews = fact_reviews.merge(dim_sentiment, on="sentiment_label", how="left")
fact_reviews = fact_reviews.merge(dim_ux, on="ux_sentiment_level", how="left")

# List of potential columns to include
candidate_columns = [
    "review_date", "rating", "rating_category", "review_text",
    "review_length", "has_reply", "sentiment_score", "sentiment_label",
    "csat_approx", "ces_approx", "task_success_inferred",
    "ux_health_score", "ux_sentiment_level", "ux_pain_point_flag",
    "is_pseudonymized", "platform_id", "version_id", "date_id", "sentiment_id"
]

# Keep only columns that exist in the dataframe
existing_columns = [col for col in candidate_columns if col in fact_reviews.columns]

# Select only valid ones
fact_reviews = fact_reviews[existing_columns]

print(f"✅ FactReviews shape: {fact_reviews.shape}")
fact_reviews.head(3)

🧮 Building FactReviews table...
✅ FactReviews shape: (31625, 18)

,review_date,rating,rating_category,review_text,review_length,has_reply,sentiment_score,sentiment_label,csat_approx,ces_approx,task_success_inferred,ux_health_score,ux_sentiment_level,ux_pain_point_flag,platform_id,version_id,date_id,sentiment_id
0,2025-10-01 06:03:52+00:00,5,High,This banking app is the best for kids because ...,411,0,0.9578,positive,99.16,65,NaN,0.9578,Positive,False,1,1,31615,1
1,2025-09-30 15:17:27+00:00,5,High,Don’t tend to use the perks other than get sue...,125,0,0.7650,positive,95.30,85,NaN,0.7650,Positive,False,1,1,31614,1
2,2025-09-30 15:01:26+00:00,5,High,The best bank I have ever use. It is honestly ...,75,0,0.9432,positive,98.86,65,NaN,NaN,Unknown,False,1,1,31613,1

In [10]:
from IPython.display import display

print("Dim Shapes")

display(fact_reviews.head(3))
display(dim_platform.head(3))
display(dim_version.head(3))
display(dim_date.head(3))
display(dim_sentiment.head(3))
display(dim_ux.head(3))

Dim Shapes

,review_date,rating,rating_category,review_text,review_length,has_reply,sentiment_score,sentiment_label,csat_approx,ces_approx,task_success_inferred,ux_health_score,ux_sentiment_level,ux_pain_point_flag,platform_id,version_id,date_id,sentiment_id
0,2025-10-01 06:03:52+00:00,5,High,This banking app is the best for kids because ...,411,0,0.9578,positive,99.16,65,NaN,0.9578,Positive,False,1,1,31615,1
1,2025-09-30 15:17:27+00:00,5,High,Don’t tend to use the perks other than get sue...,125,0,0.7650,positive,95.30,85,NaN,0.7650,Positive,False,1,1,31614,1
2,2025-09-30 15:01:26+00:00,5,High,The best bank I have ever use. It is honestly ...,75,0,0.9432,positive,98.86,65,NaN,NaN,Unknown,False,1,1,31613,1

  platform  platform_id
0      iOS            1
1  Android            2

  app_version  version_id
0      6.46.0           1
1      6.45.0           2
2      6.44.0           3

                review_date  review_year  review_month  review_week  date_id
0 2016-02-26 22:15:55+00:00         2016             2            8        1
1 2016-03-01 19:48:37+00:00         2016             3            9        2
2 2016-03-03 14:56:53+00:00         2016             3            9        3

  sentiment_label  sentiment_id
0        positive             1
1         neutral             2
2        negative             3

  ux_sentiment_level  ux_id
0           Positive      1
1            Unknown      2
2            Neutral      3

In [11]:
dim_ux = monzo_df[[
    "ux_usability_sentiment",
    "ux_navigation_sentiment",
    "ux_performance_sentiment",
    "ux_accessibility_sentiment",
    "ux_emotional_sentiment",
    "ux_health_score",
    "ux_pain_point_flag",
    "ux_sentiment_level"
]].drop_duplicates().reset_index(drop=True)

dim_ux["ux_id"] = dim_ux.index + 1

In [12]:
fact_reviews = fact_reviews.merge(dim_ux, on="ux_sentiment_level", how="left")

In [13]:
from IPython.display import display

print("Dim Shapes")

display(fact_reviews.head(3))
display(dim_platform.head(3))
display(dim_version.head(3))
display(dim_date.head(3))
display(dim_sentiment.head(3))
display(dim_ux.head(3))

Dim Shapes

,review_date,rating,rating_category,review_text,review_length,has_reply,sentiment_score,sentiment_label,csat_approx,ces_approx,...,date_id,sentiment_id,ux_usability_sentiment,ux_navigation_sentiment,ux_performance_sentiment,ux_accessibility_sentiment,ux_emotional_sentiment,ux_health_score_y,ux_pain_point_flag_y,ux_id
0,2025-10-01 06:03:52+00:00,5,High,This banking app is the best for kids because ...,411,0,0.9578,positive,99.16,65,...,31615,1,NaN,NaN,NaN,0.9578,0.9578,0.9578,False,1
1,2025-10-01 06:03:52+00:00,5,High,This banking app is the best for kids because ...,411,0,0.9578,positive,99.16,65,...,31615,1,0.765,NaN,NaN,NaN,NaN,0.7650,False,2
2,2025-10-01 06:03:52+00:00,5,High,This banking app is the best for kids because ...,411,0,0.9578,positive,99.16,65,...,31615,1,NaN,NaN,NaN,NaN,0.8555,0.8555,False,4

  platform  platform_id
0      iOS            1
1  Android            2

  app_version  version_id
0      6.46.0           1
1      6.45.0           2
2      6.44.0           3

                review_date  review_year  review_month  review_week  date_id
0 2016-02-26 22:15:55+00:00         2016             2            8        1
1 2016-03-01 19:48:37+00:00         2016             3            9        2
2 2016-03-03 14:56:53+00:00         2016             3            9        3

  sentiment_label  sentiment_id
0        positive             1
1         neutral             2
2        negative             3

,ux_usability_sentiment,ux_navigation_sentiment,ux_performance_sentiment,ux_accessibility_sentiment,ux_emotional_sentiment,ux_health_score,ux_pain_point_flag,ux_sentiment_level,ux_id
0,NaN,NaN,NaN,0.9578,0.9578,0.9578,False,Positive,1
1,0.765,NaN,NaN,NaN,NaN,0.7650,False,Positive,2
2,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,3

In [ ]:
# ------------------------------------------------------------
# 5. Export Dimensional & Fact Tables
# ------------------------------------------------------------

import os
import pandas as pd

# --- Setup paths ---
FORMATS = ["csv", "gzip", "parquet"]
for fmt in FORMATS:
    os.makedirs(os.path.join(WAREHOUSE_PATH, fmt), exist_ok=True)

# --- Tables to export ---
tables = {
    "FactReviews": fact_reviews,
    "DimPlatform": dim_platform,
    "DimVersion": dim_version,
    "DimDate": dim_date,
    "DimSentiment": dim_sentiment,
    "DimUX": dim_ux
}

# --- Export loop ---
print("💾 Exporting all warehouse tables in CSV, GZIP, and Parquet formats...")

for name, table in tables.items():
    print(f"\n📦 Exporting {name} ({table.shape[0]} rows, {table.shape[1]} cols)...")

    # 1️⃣ CSV
    csv_path = os.path.join(WAREHOUSE_PATH, "csv", f"{name}.csv")
    table.to_csv(csv_path, index=False, encoding="utf-8")

    # 2️⃣ GZIP
    gzip_path = os.path.join(WAREHOUSE_PATH, "gzip", f"{name}.csv.gz")
    table.to_csv(gzip_path, index=False, compression="gzip", encoding="utf-8")

    # 3️⃣ Parquet
    parquet_path = os.path.join(WAREHOUSE_PATH, "parquet", f"{name}.parquet")
    table.to_parquet(parquet_path, index=False, compression="snappy")

    # Size check
    size_csv = os.path.getsize(csv_path) / (1024**3)
    size_gz = os.path.getsize(gzip_path) / (1024**3)
    size_pq = os.path.getsize(parquet_path) / (1024**3)

    print(f"   • CSV:   {size_csv:.2f} GB")
    print(f"   • GZIP:  {size_gz:.2f} GB")
    print(f"   • PARQ:  {size_pq:.2f} GB")

print("\n✅ All export formats generated successfully.")
print(f"📁 Location: {WAREHOUSE_PATH}")

💾 Exporting all warehouse tables in CSV, GZIP, and Parquet formats...

📦 Exporting FactReviews (23760394 rows, 26 cols)...